export const CHECKOUT_PAYMENT_WINDOW_MINUTES = 60;
export const CHECKOUT_RESERVATION_BUFFER_MINUTES = 5;
export const CHECKOUT_RESERVATION_WINDOW_MINUTES = CHECKOUT_PAYMENT_WINDOW_MINUTES + CHECKOUT_RESERVATION_BUFFER_MINUTES;
